# Uncomment the next line to define a global platform for your project
# platform :ios, '10.0'

target 'MangaUniver' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
pod 'Alamofire', '~> 5.2'

  # Pods for MangaUniver

  target 'MangaUniverTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'MangaUniverUITests' do
    # Pods for testing
  end

end
